CREATE TABLE FinalResult (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Ativo VARCHAR(7) NOT NULL,
    TipoAtivo INT NOT NULL,
	Nome VARCHAR(50) NULL,
    LT INT NULL,
    CFA DOUBLE(8,2) NULL,
    CAb DOUBLE(8,2) NULL,
	CFA_STP INT NULL,
    CAb_STP INT NULL,
    VFA DOUBLE(8,2) NULL,
    VAb DOUBLE(8,2) NULL,
    VFA_STP INT NULL,
    VAb_STP INT NULL
)